### ISSUE TITLE
Client shared header ui

### ISSUE THREAD

**Issue by KienVu1504** [KienVu1504/SuperCook_FE#4]
![image](https://user-images.githubusercontent.com/90754622/207900042-d30f418a-a204-4faf-a86c-31ccf52b0961.png)

assets:
`background-color: #d8456b;
`
`font-family: Nunito, sans-serif;`
`font-size: 24px;`
![vegetable_pattern](https://user-images.githubusercontent.com/90754622/208245693-b555bd6e-0efe-42c3-8b8c-774627eeea14.svg)

**Comment by behemoth-kienvt** [comment]
ai làm thì ghi tên vào để sau còn biết
